disabled_rules:
  - line_length
  - type_body_length
  - file_length
included: # paths to include during linting. `--path` is ignored if present.
  - Clappr
  - Example
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Example/Pods
  - Tests