# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
language: objective-c

osx_image: xcode9.1

before_install:
  - make setup

script:
  - swiftlint
  - pod lib lint
  - make test
