# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
language: objective-c

osx_image: xcode7.3

before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- pod update --project-directory=Example

script:
- xcodebuild test -workspace Example/Clappr.xcworkspace -scheme Clappr-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6s Plus,OS=9.2'| xcpretty
- pod lib lint
