# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
script:
- cd Example
- pod update
- xctool test -workspace Clappr.xcworkspace -scheme Clappr -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
