# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
language: objective-c

osx_image: xcode8

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --platform iOS
  - gem install cocoapods -v '1.1.1'
  - pod repo update

script:
  - xcodebuild clean test -project Clappr.xcodeproj -scheme Clappr-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6s Plus,OS=10.0'| xcpretty
  - pod lib lint
