# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.2

language: swift

before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- pod install --project-directory=Example

script:
- xcodebuild test -workspace Example/Clappr.xcworkspace -scheme Clappr-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
