# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
language: objective-c

osx_image: xcode9.1

env:
  global:
    - PROJECT="Clappr.xcodeproj"
    - SCHEME="Clappr-Example"
    - DESTINATION="platform=iOS Simulator,name=iPhone 6s Plus,OS=11.0"

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - brew outdated swiftlint || brew upgrade swiftlint
  - carthage bootstrap --platform iOS
  - gem install cocoapods -v '1.1.1'
  - pod repo update
  - gem install simctl --no-rdoc --no-ri --no-document --quiet
  - ruby -rsimctl -e 'SimCtl.warmup("iPhone 6s Plus", "iOS 11.0", 300)'

script:
  - swiftlint
  - pod lib lint
  - xcodebuild test -project "${PROJECT}" -scheme "${SCHEME}" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination "${DESTINATION}" | xcpretty -s && exit ${PIPESTATUS[0]}
