# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
language: objective-c

osx_image: xcode8.3

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --platform iOS
  - gem install cocoapods -v '1.1.1'
  - pod repo update

script:
  - bash run_tests.sh
